# Generated by Django 4.0.3 on 2022-11-29 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docman', '0002_alter_document_slug_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 6, 28, 16551), max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 6, 28, 9570), max_length=512),
        ),
        migrations.AlterField(
            model_name='event_day',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 6, 28, 12563), max_length=512),
        ),
        migrations.AlterField(
            model_name='event_session',
            name='notes',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='event_session',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 6, 28, 14558), max_length=512),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 6, 28, 14558), max_length=512),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 6, 28, 13562), max_length=512),
        ),
        migrations.AlterModelTable(
            name='event_day',
            table='docman.models',
        ),
    ]
