# Generated by Django 4.0.3 on 2022-11-29 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docman', '0003_alter_document_slug_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 9, 0, 567927), max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 9, 0, 556951), max_length=512),
        ),
        migrations.AlterField(
            model_name='event_day',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 9, 0, 560940), max_length=512),
        ),
        migrations.AlterField(
            model_name='event_session',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 9, 0, 564929), max_length=512),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 9, 0, 565927), max_length=512),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 11, 9, 0, 563933), max_length=512),
        ),
        migrations.AlterModelTable(
            name='event_day',
            table='test',
        ),
    ]
