# Generated by Django 4.0.3 on 2022-11-29 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docman', '0005_alter_document_slug_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 16, 31, 48, 196803), max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 16, 31, 48, 190819), max_length=512),
        ),
        migrations.AlterField(
            model_name='event_day',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 16, 31, 48, 192814), max_length=512),
        ),
        migrations.AlterField(
            model_name='event_session',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 16, 31, 48, 194808), max_length=512),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 16, 31, 48, 194808), max_length=512),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 11, 29, 16, 31, 48, 194808), max_length=512),
        ),
    ]
